import React, { useRef, useState } from 'react';
import { ArrowRight, CheckCircle2, KeyRound, Lock, Mail } from 'lucide-react';
import { AnimatePresence, motion } from 'framer-motion';
import { Link, useNavigate } from 'react-router-dom';
import { authService } from '../../../services/authService';
import { AuthError, AuthInput, AuthShell } from '../components/AuthShell';

const PasswordReset: React.FC = () => {
  const [step, setStep] = useState(1); const [email, setEmail] = useState(''); const [otp, setOtp] = useState(Array(6).fill('')); const [token, setToken] = useState(''); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const refs = useRef<Array<HTMLInputElement | null>>([]); const navigate = useNavigate();
  const run = async (task: () => Promise<void>) => { setLoading(true); setError(''); try { await task(); } catch (err: any) { setError(err.message || 'Không thể xử lý yêu cầu. Vui lòng thử lại.'); } finally { setLoading(false); } };
  const requestOtp = (event: React.FormEvent) => { event.preventDefault(); run(async () => { await authService.forgotPassword(email); setStep(2); }); };
  const verifyOtp = (event: React.FormEvent) => { event.preventDefault(); run(async () => { const result = await authService.verifyResetOtp(email, otp.join('')); setToken(result.resetToken); setStep(3); }); };
  const reset = (event: React.FormEvent) => { event.preventDefault(); if (password !== confirm) return setError('Mật khẩu xác nhận không khớp.'); run(async () => { await authService.resetPassword(email, token, password); setStep(4); }); };
  const changeOtp = (index: number, value: string) => { const digit = value.replace(/\D/g, '').slice(-1); const next = [...otp]; next[index] = digit; setOtp(next); if (digit && index < 5) refs.current[index + 1]?.focus(); };
  return <AuthShell title="Khôi phục tài khoản thật nhẹ nhàng." text="Mã OTP giúp xác nhận đúng tài khoản trước khi tạo mật khẩu mới. Mỗi mã chỉ dùng một lần và hết hạn sau ít phút."><div className="mx-auto max-w-md"><div className="mb-6 flex gap-2">{[1, 2, 3].map((value) => <span key={value} className={`h-1.5 flex-1 rounded-full transition-colors ${Math.min(step, 3) >= value ? 'bg-blue-700' : 'bg-slate-100'}`} />)}</div><AnimatePresence mode="wait"><motion.div key={step} initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -20 }} transition={{ duration: 0.2 }}>
    <p className="text-xs font-black uppercase tracking-widest text-blue-700">Bước {Math.min(step, 3)} / 3</p>
    {step === 1 && <form onSubmit={requestOtp} className="mt-3 space-y-5"><h2 className="text-3xl font-black">Quên mật khẩu?</h2><p className="text-sm font-semibold leading-6 text-slate-500">Nhập email đã đăng ký để nhận mã OTP.</p><AuthError message={error} /><AuthInput required type="email" label="Email tài khoản" value={email} onChange={e => setEmail(e.target.value)} placeholder="name@example.com" icon={<Mail size={17} />} /><Action loading={loading}>Gửi mã OTP</Action></form>}
    {step === 2 && <form onSubmit={verifyOtp} className="mt-3 space-y-5"><h2 className="text-3xl font-black">Nhập mã OTP</h2><p className="text-sm font-semibold leading-6 text-slate-500">Mã xác nhận gồm 6 số đã được gửi tới <strong>{email}</strong>.</p><AuthError message={error} /><div className="grid grid-cols-6 gap-2">{otp.map((value, index) => <input key={index} ref={node => { refs.current[index] = node; }} value={value} onChange={e => changeOtp(index, e.target.value)} inputMode="numeric" maxLength={1} className="h-12 rounded-xl border border-slate-200 bg-slate-50 text-center text-lg font-black outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-500/10" />)}</div><Action loading={loading}>Xác minh OTP</Action><button type="button" onClick={() => setStep(1)} className="w-full text-xs font-black text-blue-700">Đổi email nhận mã</button></form>}
    {step === 3 && <form onSubmit={reset} className="mt-3 space-y-5"><h2 className="text-3xl font-black">Tạo mật khẩu mới</h2><p className="text-sm font-semibold leading-6 text-slate-500">Dùng ít nhất 8 ký tự và tránh mật khẩu dễ đoán.</p><AuthError message={error} /><AuthInput required minLength={8} type="password" label="Mật khẩu mới" value={password} onChange={e => setPassword(e.target.value)} placeholder="••••••••" icon={<Lock size={17} />} /><AuthInput required minLength={8} type="password" label="Xác nhận mật khẩu" value={confirm} onChange={e => setConfirm(e.target.value)} placeholder="••••••••" icon={<KeyRound size={17} />} /><Action loading={loading}>Lưu mật khẩu mới</Action></form>}
    {step === 4 && <div className="py-8 text-center"><CheckCircle2 size={54} className="mx-auto text-emerald-600" /><h2 className="mt-4 text-3xl font-black">Đổi mật khẩu thành công</h2><p className="mt-3 text-sm font-semibold text-slate-500">Bạn có thể đăng nhập bằng mật khẩu mới ngay bây giờ.</p><button type="button" onClick={() => navigate('/login')} className="mt-6 h-12 rounded-xl bg-blue-700 px-5 text-sm font-black text-white">Về trang đăng nhập</button></div>}
    {step < 4 && <p className="mt-6 text-center text-sm font-semibold text-slate-500">Đã nhớ mật khẩu? <Link to="/login" className="font-black text-blue-700">Đăng nhập</Link></p>}
  </motion.div></AnimatePresence></div></AuthShell>;
};
const Action = ({ children, loading }: React.PropsWithChildren<{ loading: boolean }>) => <button disabled={loading} className="flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-blue-700 text-sm font-black text-white hover:bg-blue-800 disabled:opacity-50">{loading ? 'Đang xử lý...' : <>{children}<ArrowRight size={17} /></>}</button>;
export default PasswordReset;
