import React from 'react';
import { ArrowRight, CheckCircle2, Quote, Star } from 'lucide-react';
import { Link } from 'react-router-dom';

const reviews = [
  { name: 'Minh Anh', detail: 'Người chơi cầu lông · Trà Vinh', rating: 5, image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=160&q=85', text: 'Đặt sân rất nhanh, xem được giá và giờ trống trước khi cọc. Mọi thay đổi đều có thông báo trong hồ sơ.' },
  { name: 'Tuấn Khang', detail: 'Đội trưởng bóng đá', rating: 5, image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=160&q=85', text: 'Cả đội chọn giờ dễ hơn vì link sân có đủ khung giờ, vị trí và giá. Không còn phải gọi hỏi từng sân.' },
  { name: 'Hoàng Nam', detail: 'Chủ cụm sân thể thao', rating: 4, image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=160&q=85', text: 'Sân nào đang nhận lịch, khoản cọc nào cần theo dõi đều hiển thị rất rõ trong khu vực quản lý.' },
];

const CommunityStoriesSection: React.FC = () => <>
  <section className="bg-blue-950 py-16 text-slate-50 sm:py-20"><div className="mx-auto grid max-w-7xl gap-8 px-5 sm:px-6 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><div><p className="text-xs font-black uppercase tracking-widest text-blue-200">Đặt sân theo cách rõ ràng hơn</p><h2 className="mt-3 max-w-xl text-3xl font-black leading-tight text-slate-50 sm:text-4xl">Ít thời gian xác nhận, nhiều thời gian cho trận đấu.</h2><p className="mt-5 max-w-xl text-sm font-semibold leading-7 text-blue-100">Từ tìm sân đến trả cọc, thông tin được đặt theo đúng trình tự người dùng cần quyết định.</p><div className="mt-7 space-y-3 text-sm font-bold text-blue-50"><p className="flex gap-2"><CheckCircle2 size={18} className="shrink-0 text-emerald-300" />So sánh sân bằng giá, đánh giá và vị trí</p><p className="flex gap-2"><CheckCircle2 size={18} className="shrink-0 text-emerald-300" />Giữ lịch, thanh toán cọc và theo dõi đơn trong một luồng</p></div><Link to="/explore" className="mt-8 inline-flex items-center gap-2 rounded-xl bg-amber-300 px-4 py-3 text-sm font-black text-blue-950 hover:bg-amber-200">Tìm sân ngay <ArrowRight size={16} /></Link></div><div className="grid grid-cols-2 gap-3"><img src="https://images.unsplash.com/photo-1575361204480-aadea25e6e68?auto=format&fit=crop&w=1200&q=85" alt="Sân bóng đá" className="col-span-2 h-64 w-full rounded-2xl object-cover sm:h-72" /><img src="https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&w=700&q=85" alt="Sân cầu lông" className="h-36 w-full rounded-2xl object-cover" /><img src="https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=700&q=85" alt="Sân bóng rổ" className="h-36 w-full rounded-2xl object-cover" /><div className="col-span-2 grid gap-3 rounded-2xl border border-blue-800 bg-blue-900 p-4 text-sm font-bold sm:grid-cols-3"><p>Đủ thông tin trước khi đặt</p><p className="text-blue-100">Lịch trống theo ngày và giờ</p><p className="text-blue-100">Vận hành ngay trên dashboard</p></div></div></div></section>
  <section className="bg-slate-50 py-16 sm:py-20"><div className="mx-auto max-w-7xl px-5 sm:px-6"><div className="max-w-2xl"><p className="text-xs font-black uppercase tracking-widest text-blue-700">Khách hàng nhận xét</p><h2 className="mt-3 text-3xl font-black tracking-tight text-slate-950 sm:text-4xl">Những trải nghiệm sau khi đặt sân.</h2></div><div className="mt-8 grid gap-4 lg:grid-cols-3">{reviews.map((review) => <article key={review.name} className="border border-slate-200 bg-white p-5 shadow-sm"><Quote size={22} className="text-blue-600" /><p className="mt-5 min-h-28 text-sm font-semibold leading-7 text-slate-700">“{review.text}”</p><div className="mt-5 flex gap-0.5 text-amber-500">{Array.from({ length: 5 }).map((_, index) => <Star key={index} size={15} className={index < review.rating ? 'fill-current' : 'text-slate-200'} />)}</div><div className="mt-5 flex items-center gap-3 border-t border-slate-100 pt-4"><img src={review.image} alt="" className="h-10 w-10 rounded-full object-cover" /><div><p className="text-sm font-black text-slate-950">{review.name}</p><p className="mt-0.5 text-xs font-semibold text-slate-500">{review.detail}</p></div></div></article>)}</div></div></section>
</>;

export default CommunityStoriesSection;
